export const SUBMIT_RECORD = 'SUBMIT_RECORD';
export const CLEAR_RECORD = 'CLEAR_RECORD';
export const SELECT_RECORD_TAB = 'SELECT_RECORD_TAB';
export const SELECT_RECORD_TYPE = 'SELECT_RECORD_TYPE';
export const ENTER_RECORD_MONEY = 'ENTER_RECORD_MONEY';
export const ENTER_RECORD_DATE = 'ENTER_RECORD_DATE';
export const ENTER_RECORD_SUMMARY = 'ENTER_RECORD_SUMMARY';
export const DISPLAY_RECORD_ERROR = 'DISPLAY_ERROR';
