/**
 * Record Enums
 */
export const CLEAR_RECORD = 'CLEAR_RECORD';
export const SELECT_RECORD_TAB = 'SELECT_RECORD_TAB';
export const SELECT_RECORD_TYPE = 'SELECT_RECORD_TYPE';
export const ENTER_RECORD_MONEY = 'ENTER_RECORD_MONEY';
export const ENTER_RECORD_DATE = 'ENTER_RECORD_DATE';
export const ENTER_RECORD_SUMMARY = 'ENTER_RECORD_SUMMARY';
export const DISPLAY_RECORD_ERROR = 'DISPLAY_ERROR';
export const SELECT_RECORD_GROUP = 'SELECT_RECORD_GROUP';
export const CREATE_NEW_GROUP = 'CREATE_NEW_GROUP';
export const CREATE_NEW_TYPE = 'CREATE_NEW_TYPE';
export const ON_USER_LOGIN = 'ON_USER_LOGIN';
export const ON_MODAL_OPEN = 'ON_MODAL_OPEN';
export const ON_MODAL_CLOSE = 'ON_MODAL_CLOSE';
export const FETCH_RECORD_GROUPS = 'FETCH_RECORD_GROUPS';

/**
 * Review Enums
 */
export const FETCH_RECORDS = 'FETCH_RECORDS';

/**
 * Modal Enums
 */
export const ALERT_MODAL = 'ALERT_MODAL';
export const SUCCESS_MODAL = 'SUCCESS_MODAL';
